version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always

  backend:
    image: ghcr.io/pbvoraprat1/warehouseos-backend:latest
    env_file:
      - .env
    environment:
      - DEBUG=0
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - ALLOWED_HOSTS=159.89.200.8,warehouseos.duckdns.org,backend,localhost
    depends_on:
      - db
    restart: always
    command: gunicorn inventory.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  frontend:
    image: ghcr.io/pbvoraprat1/warehouseos-frontend:latest
    restart: always
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: warehouseos-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/var/www/inventory/static
      - media_volume:/var/www/inventory/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_volume:
  media_volume:
