# Generated by Django 6.0.1 on 2026-07-03 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_warehouses', models.BooleanField(default=False, verbose_name='สิทธิ์จัดการคลังสินค้า (Action)')),
                ('can_manage_products', models.BooleanField(default=False, verbose_name='สิทธิ์จัดการสินค้า (Action)')),
                ('can_manage_auto_reorder', models.BooleanField(default=False, verbose_name='สิทธิ์ตั้งค่า Auto Reorder')),
                ('can_manage_stock_movements', models.BooleanField(default=False, verbose_name='สิทธิ์จัดการการเคลื่อนไหวสินค้า (Action)')),
                ('can_view_activity_logs', models.BooleanField(default=False, verbose_name='สิทธิ์ดู Activity Log (View)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
