name : CICD CI/CD Pipeline for WarehouseOS to DigitalOcean

on:
  push:
    branches:
      - main

#Test Backend

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: warehouse-test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_NAME: warehouse-test
      SECRET_KEY: test-secret-key-for-testing
      ALLOWED_HOSTS: '*'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
        
      - name: Install Backend Dependencies
        run : pip install -r requirements.txt
      
      - name: Run Django Unit Tests
        run: python manage.py test

#Test Frontend

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
      
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend Tests (Vitest)
        run: |
          cd frontend
          npm test
  build-and-push:
    needs: [test-backend, test-frontend]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    step:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/pbvoraprat1/warehouseos-backend:latest
      
      - name: Build & Push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: Dockerfile
          push: true
          tags: ghcr.io/pbvoraprat1/warehouseos-frontend:latest
          buildargs: |
            VITE_API_BASE_URL=https://warehouseos.duckdns.org
          cache-from: type=gha
          cache-to: type=gha,mode=max   

#Deploy to DigitalOcean
  deploy:
    needs: [test-backend, test-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/WarehouseOS
            git pull origin main
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u pbvoraprat1 --password-stdin
            docker compose -f docker-compose.prod.yml build
            docker compose -f docker-compose.prod.yml up -d
            docker image prune -f